Feature/asset manager
SE2-Mankomania-SS20/Mankomania pull request #52
Opened 2020-05-05 16:49 UTC by moitzi

Hab zwei Klassen erstellt "AssetDescriptors" und "AssetPaths". Laut Recherche ist dieser Weg der "Sauberste".  AssetDescriptors schreibt vor das Assets mit FileName und Type geladen werden müssen. Falls Änderungen bei den Pfaden etc auftauchen, muss man es nur an einem Ort ändern. Ich habe an ein paar Stellen schon die Textures mit AssetManager geladen, aber ich hab bestimmt ein paar Sachen übersehen so wie Fonts. Als Probelauf habe ich es in den Screens ersetzt und im FieldOverlayTextures.

2020-05-06 17:41 UTC, fischly requested changes
Besser wäre ein globaler/zentraler Asset Manager, der alle Assets am Start des Spieles laden kann (um gegebenenfalls später einen LoadingScreen zu implementieren).

2020-05-07 12:16 UTC, orazefabian requested changes
genau des was der felix schon requestet hat

2020-05-26 18:50 UTC, orazefabian submitted a review, later dismissed
approving myself

2020-05-26 19:18 UTC, fischly approved these changes
asset manager finally working ^__^

2020-05-26 19:20 UTC, merged